services:
  Tailr\SuluTranslationsBundle\Infrastructure\Doctrine\Repository\DoctrineTranslationRepository:
    arguments:
      - '@Tailr\SuluTranslationsBundle\Infrastructure\Doctrine\DatabaseConnectionManager'
      - '@Tailr\SuluTranslationsBundle\Infrastructure\Doctrine\Mapper\TranslationMapper'
  Tailr\SuluTranslationsBundle\Domain\Repository\TranslationRepository: '@Tailr\SuluTranslationsBundle\Infrastructure\Doctrine\Repository\DoctrineTranslationRepository'